# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tiot.proto\"\xbe\x01\n\nSensorData\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x10\n\x08pressure\x18\x03 \x01(\x02\x12\"\n\x06status\x18\x04 \x01(\x0e\x32\x12.SensorData.Status\x12\x13\n\x0btemperature\x18\x05 \x01(\x05\"@\n\x06Status\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x06\n\x02ON\x10\x01\x12\x07\n\x03OFF\x10\x02\x12\n\n\x06\x41\x43TIVE\x10\x03\x12\x0c\n\x08INACTIVE\x10\x04\"\x1c\n\x05Reply\x12\x13\n\x0breturnValue\x18\x01 \x01(\x05\"\x1c\n\x08SensorId\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\"#\n\x0cSensorStatus\x12\x13\n\x0bstatus_freq\x18\x01 \x03(\x05\"!\n\rSensorHistory\x12\x10\n\x08statuses\x18\x01 \x03(\x05\"\x16\n\x05\x46ield\x12\r\n\x05\x66ield\x18\x01 \x01(\t\")\n\x0bTopSensorId\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\r\n\x05\x66ield\x18\x02 \x03(\x02\x32\xc2\x01\n\tIotSender\x12(\n\rGetSensorData\x12\x0b.SensorData\x1a\x06.Reply\"\x00(\x01\x12.\n\x10SendSensorStatus\x12\t.SensorId\x1a\r.SensorStatus\"\x00\x12\x30\n\x11SendSensorHistory\x12\t.SensorId\x1a\x0e.SensorHistory\"\x00\x12)\n\x0fSendTopSensorId\x12\x06.Field\x1a\x0c.TopSensorId\"\x00\x62\x06proto3')



_SENSORDATA = DESCRIPTOR.message_types_by_name['SensorData']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
_SENSORID = DESCRIPTOR.message_types_by_name['SensorId']
_SENSORSTATUS = DESCRIPTOR.message_types_by_name['SensorStatus']
_SENSORHISTORY = DESCRIPTOR.message_types_by_name['SensorHistory']
_FIELD = DESCRIPTOR.message_types_by_name['Field']
_TOPSENSORID = DESCRIPTOR.message_types_by_name['TopSensorId']
_SENSORDATA_STATUS = _SENSORDATA.enum_types_by_name['Status']
SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:SensorData)
  })
_sym_db.RegisterMessage(SensorData)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)

SensorId = _reflection.GeneratedProtocolMessageType('SensorId', (_message.Message,), {
  'DESCRIPTOR' : _SENSORID,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:SensorId)
  })
_sym_db.RegisterMessage(SensorId)

SensorStatus = _reflection.GeneratedProtocolMessageType('SensorStatus', (_message.Message,), {
  'DESCRIPTOR' : _SENSORSTATUS,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:SensorStatus)
  })
_sym_db.RegisterMessage(SensorStatus)

SensorHistory = _reflection.GeneratedProtocolMessageType('SensorHistory', (_message.Message,), {
  'DESCRIPTOR' : _SENSORHISTORY,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:SensorHistory)
  })
_sym_db.RegisterMessage(SensorHistory)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
  'DESCRIPTOR' : _FIELD,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:Field)
  })
_sym_db.RegisterMessage(Field)

TopSensorId = _reflection.GeneratedProtocolMessageType('TopSensorId', (_message.Message,), {
  'DESCRIPTOR' : _TOPSENSORID,
  '__module__' : 'iot_pb2'
  # @@protoc_insertion_point(class_scope:TopSensorId)
  })
_sym_db.RegisterMessage(TopSensorId)

_IOTSENDER = DESCRIPTOR.services_by_name['IotSender']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATA._serialized_start=14
  _SENSORDATA._serialized_end=204
  _SENSORDATA_STATUS._serialized_start=140
  _SENSORDATA_STATUS._serialized_end=204
  _REPLY._serialized_start=206
  _REPLY._serialized_end=234
  _SENSORID._serialized_start=236
  _SENSORID._serialized_end=264
  _SENSORSTATUS._serialized_start=266
  _SENSORSTATUS._serialized_end=301
  _SENSORHISTORY._serialized_start=303
  _SENSORHISTORY._serialized_end=336
  _FIELD._serialized_start=338
  _FIELD._serialized_end=360
  _TOPSENSORID._serialized_start=362
  _TOPSENSORID._serialized_end=403
  _IOTSENDER._serialized_start=406
  _IOTSENDER._serialized_end=600
# @@protoc_insertion_point(module_scope)
